convert:
  #!/Users/denis/.juliaup/bin/julia

  import Pkg; Pkg.activate(".")
  import HexToCterm; HexToCterm.convert()

update-packages:
  #!/Users/denis/.juliaup/bin/julia
  import Pkg; Pkg.activate(".")
  Pkg.Registry.update(); Pkg.update()
